### ISSUE TITLE
Proposition: take my Todoist API v8 implementation

### ISSUE THREAD

**Issue by romgrk** [moranje/todoist-rest-api#53]
Hey, I've implemented version 8 of the todoist API because I needed it for a project I'm building. I'm too lazy to publish it in it's own module and it would suck to add yet another todoist module on NPM. If you'd like to take my implementation and publish it in your module it would be awesome because:
 - It doesn't require any effort on my part
 - People get the latest version of the API
 - You get additional glory

Reasons for making this proposition to you instead of other todoist modules:
 - Your module seems to be the only usable implementation out there

Competing modules for the proposition:
 - https://github.com/mtalstykh/todoist-nodejs/issues/4

It's a single 200 untested lines file: https://github.com/romgrk/todoist.nvim/blob/master/src/todoist.js
License: MIT

**Comment by moranje** [comment]
Hi! I appreciate the offer. However this is a one module based on their REST API (also the latest version). I would think a module based on their sync API would be better suited to share your implementation with?

**Comment by romgrk** [comment]
Got it, I hadn't realized the difference REST vs SYNC, it's clearer now. Actually I got the owner of the `todoist` package to transfer it to me, so if I can overcome my lazyness I will upload it there ^^
